name: julio33

on:

        Push:
        workflow_dispatch:

jobs:

  build:

     runs-on: ubuntu-latest

     steps:

         - uses: actions/checkout@v3

         - name: run a multi-line script
           run: |
              echo "hola mundo"

test:
   needs: build
   runs-on: ubuntu-latest

steps:

  - name: Hola
    run: | 
       echo "hola"
